[general]
# Whether to hide empty columns or not
auto_hide = false

# Possible values: Red, Green, Blue, Yellow, Magenta, Cyan.
# Use prefix "Light" for a brighter color.
# It can also be a hex, e.g. "#3cb371"
accent_color = "LightMagenta"

# If enabled, shows various keybindings throughout the program at the cost of
# a little bit cluttered interface.
beginner_mode = true

# If enabled, hides header row of torrents tab
hide_headers = false

[connection]
url = "http://CHANGE_ME:9091/transmission/rpc" # REQUIRED!

# If you need username and password to authenticate:
# username = "CHANGE_ME"
# password = "CHANGE_ME"


