[general]
keybindings = [
  { on = "?", action = "ShowHelp", show_in_help = false },
  { on = "F1", action = "ShowHelp", show_in_help = false },

  { on = "q", action = "Quit" },
  { on = "Esc", action = "Close" },
  { on = "Enter", action = "Confirm" },
  { on = " ", action = "Select" },
  { on = "Tab", action = "SwitchFocus" },
  { on = "/", action = "Search" },
  { on = "o", action = "XdgOpen" },
  
  { on = "1", action = "SwitchToTorrents" },
  { on = "2", action = "SwitchToSearch" },

  { on = "Home", action = "GoToBeginning" },
  { on = "End", action = "GoToEnd" },
  { on = "PageUp", action = "ScrollPageUp", show_in_help = false },
  { on = "PageDown", action = "ScrollPageDown", show_in_help = false },

  { modifier = "Ctrl", on = "u", action = "ScrollPageUp" },
  { modifier = "Ctrl", on = "d", action = "ScrollPageDown" },

  # Arrows
  { on = "Left", action = "Left" },
  { on = "Right", action = "Right" },
  { on = "Up", action = "Up"},
  { on = "Down", action = "Down" },

  # Vi
  { on = "h", action = "Left" },
  { on = "l", action = "Right" },
  { on = "k", action = "Up" },
  { on = "j", action = "Down" },

  # Sorting
  { on = "H", action = "MoveToColumnLeft"},
  { on = "L", action = "MoveToColumnRight"},
]

[torrents_tab]
keybindings = [
  { on = "a", action = "AddMagnet" },
  { on = "m", action = "MoveTorrent" },
  { on = "c", action = "ChangeCategory" },
  { on = "p", action = "Pause" },
  { on = "f", action = "ShowFiles" },
  { on = "s", action = "ShowStats" },

  { on = "d", action = "Delete" },
]

[search_tab]
keybindings = [
  { on = "p", action = "ShowProvidersInfo" }
]

